name: usulicius_kelompok_lucky
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  provider: ^6.1.2
  flutter:
    sdk: flutter

  firebase_core: ^4.2.1
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  firebase_analytics: ^12.0.4
  shared_preferences: ^2.5.3
  pinput: ^5.0.2
  image_picker: ^1.2.1
  cloud_functions: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
      - assets/images/

  uses-material-design: true
